name: Pip
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: Build with Pip
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Set min macOS version
      if: runner.os == 'macOS'
      run: |
        echo "MACOSX_DEPLOYMENT_TARGET=10.15" >> $GITHUB_ENV
    
    - name: Install Linux dependencies with Clang
      if: runner.os == 'Linux'
      run: |
        sudo apt update

        sudo apt install -y \
          build-essential \
          cmake \
          ninja-build \
          libfreetype6-dev \
          libx11-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxi-dev \
          libudev-dev \
          mesa-common-dev \
          libglu1-mesa-dev \
          libflac-dev \
          libogg-dev \
          libvorbis-dev
        
    - name: Build and install
      run: |
        python -m pip install pytest
        pip install --verbose .
    
    - name: Test
      run: python -m pytest