name: Wheels
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - master
  release:
    types:
      - published
jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
   
    - name: Install system dependencies for SDist
      run: |
        sudo apt-get update
        
        sudo apt-get install -y software-properties-common wget
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main"
        sudo apt-get update

        sudo apt-get install -y \
          clang-18 \
          clang++-18 \
          clang-tools-18 \
          libc++-18-dev \
          libc++abi-18-dev

        sudo apt-get install -y \
          cmake \
          ninja-build \
          libfreetype6-dev \
          libx11-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxi-dev \
          libudev-dev \
          mesa-common-dev \
          libglu1-mesa-dev \
          libflac-dev \
          libogg-dev \
          libvorbis-dev \
          libasound2-dev
       
    - name: Build SDist
      run: pipx run build --sdist
      env:
        CC: clang
        CXX: clang++
   
    - name: Check metadata
      run: pipx run twine check dist/*
   
    - uses: actions/upload-artifact@v4
      with:
        name: dist-sdist
        path: dist/*.tar.gz
  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
   
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
   
    - uses: pypa/cibuildwheel@v2.22
      env:
        # Linux-specific setup with Clang
        CIBW_BEFORE_ALL_LINUX: |
          apt-get update &&
          apt-get install -y software-properties-common wget &&
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - &&
          add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main" &&
          apt-get update &&
          apt-get install -y \
            clang-18 \
            clang++-18 \
            clang-tools-18 \
            libc++-18-dev \
            libc++abi-18-dev &&
          apt-get install -y \
            cmake \
            ninja-build \
            libfreetype6-dev \
            libx11-dev \
            libxrandr-dev \
            libxcursor-dev \
            libxi-dev \
            libudev-dev \
            mesa-common-dev \
            libglu1-mesa-dev \
            libflac-dev \
            libogg-dev \
            libvorbis-dev \
            libasound2-dev
        # Use Clang only on Linux
        CIBW_ENVIRONMENT_LINUX: CC=clang CXX=clang++
        CIBW_ENVIRONMENT_PASS_LINUX: CC CXX
        CIBW_BUILD: "cp313-*"
   
    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash
   
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        path: wheelhouse/*.whl
        name: dist-${{ matrix.os }}
  upload_all:
    name: Upload if release
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
   
    steps:
    - uses: actions/setup-python@v5
   
    - uses: actions/download-artifact@v4
      with:
        path: dist
        pattern: dist-*
        merge-multiple: true
   
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}