name: Wheels
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - master
  release:
    types:
      - published

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
   
    - name: Install system dependencies for SDist (with GCC >= 14)
      run: |
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt install -y gcc-14 g++-14
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100 \
                                 --slave /usr/bin/g++ g++ /usr/bin/g++-14

        sudo apt install -y \
          cmake \
          ninja-build \
          libfreetype6-dev \
          libx11-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxi-dev \
          libudev-dev \
          mesa-common-dev \
          libglu1-mesa-dev \
          libflac-dev \
          libogg-dev \
          libvorbis-dev \
          libasound2-dev
       
    - name: Build SDist
      run: pipx run build --sdist
   
    - name: Check metadata
      run: pipx run twine check dist/*
   
    - uses: actions/upload-artifact@v4
      with:
        name: dist-sdist
        path: dist/*.tar.gz

  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
   
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
   
    - uses: pypa/cibuildwheel@v2.22
      env:
        # Linux-specific setup with GCC >= 14
        CIBW_BEFORE_ALL_LINUX: |
          yum install -y gcc-toolset-14 gcc-toolset-14-gcc gcc-toolset-14-g++
          source /opt/rh/gcc-toolset-14/enable

          yum install -y \
            cmake \
            ninja-build \
            freetype-devel \
            libX11-devel \
            libXrandr-devel \
            libXcursor-devel \
            libXi-devel \
            systemd-devel \
            mesa-libGL-devel \
            mesa-libGLU-devel \
            flac-devel \
            libogg-devel \
            libvorbis-devel \
            alsa-lib-devel
        CIBW_BUILD: "cp313-*"
   
    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash
   
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        path: wheelhouse/*.whl
        name: dist-${{ matrix.os }}

  upload_all:
    name: Upload if release
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
   
    steps:
    - uses: actions/setup-python@v5
   
    - uses: actions/download-artifact@v4
      with:
        path: dist
        pattern: dist-*
        merge-multiple: true
   
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
